import { jsPDF } from "jspdf";

export function generateFTALetter(estimatedPenalty) {
  const doc = new jsPDF("p", "pt", "letter");
  
  // Styling constants
  const margin = 54;
  const lineHeight = 16;
  const font = "times";
  
  // Helper to format currency
  const fmt = (n) => "$" + Math.round(n).toLocaleString();

  // Header
  doc.setFont(font, "normal");
  doc.setFontSize(12);
  
  let y = margin;
  
  doc.text("Date: _________________________", margin, y);
  y += lineHeight * 2;
  
  doc.text("Internal Revenue Service", margin, y);
  y += lineHeight;
  doc.text("Ogden, UT 84201-0027", margin, y); // Generic IRS service center address
  y += lineHeight * 2;
  
  doc.text("RE: Request for Penalty Abatement under First-Time Abate (FTA) Policy", margin, y);
  y += lineHeight;
  doc.text("Taxpayer Name: _________________________________", margin, y);
  y += lineHeight;
  doc.text("Social Security Number: _________________________", margin, y);
  y += lineHeight;
  doc.text("Tax Year: 2024", margin, y);
  y += lineHeight;
  doc.text("Form: 1040", margin, y);
  y += lineHeight * 2;
  
  doc.text("To Whom It May Concern:", margin, y);
  y += lineHeight * 2;
  
  // Body Paragraphs
  const p1 = `I am writing to formally request an abatement of the Failure to File and/or Failure to Pay penalty assessed on my 2024 Form 1040. The estimated penalty amount is approximately ${fmt(estimatedPenalty)}.`;
  const splitP1 = doc.splitTextToSize(p1, 612 - (margin * 2));
  doc.text(splitP1, margin, y);
  y += splitP1.length * lineHeight + lineHeight;
  
  const p2 = "I am requesting this abatement under the IRS First-Time Abate (FTA) administrative waiver (IRM 20.1.1.3.3.2.1). I meet all the criteria for this waiver, specifically:";
  const splitP2 = doc.splitTextToSize(p2, 612 - (margin * 2));
  doc.text(splitP2, margin, y);
  y += splitP2.length * lineHeight + (lineHeight / 2);
  
  // Bullet points
  const bullets = [
    "I have not been required to file a return or have no prior penalties (except the estimated tax penalty) for the preceding three tax years (2021, 2022, and 2023).",
    "I have filed, or filed a valid extension for, all currently required returns.",
    "I have paid, or arranged to pay, any tax currently due."
  ];
  
  bullets.forEach(bullet => {
    const bulletText = doc.splitTextToSize(`• ${bullet}`, 612 - (margin * 2) - 10);
    doc.text(bulletText, margin + 10, y);
    y += bulletText.length * lineHeight + (lineHeight / 2);
  });
  
  y += (lineHeight / 2);
  
  const p3 = "Because I meet the requirements of the First-Time Abate policy, I respectfully request that the penalty be removed from my account.";
  const splitP3 = doc.splitTextToSize(p3, 612 - (margin * 2));
  doc.text(splitP3, margin, y);
  y += splitP3.length * lineHeight + lineHeight * 2;
  
  // Sign-off
  doc.text("Thank you for your time and assistance in this matter.", margin, y);
  y += lineHeight * 3;
  
  doc.text("Sincerely,", margin, y);
  y += lineHeight * 3;
  
  doc.text("_________________________________________", margin, y);
  y += lineHeight;
  doc.text("(Signature)", margin, y);
  y += lineHeight * 2;
  
  doc.text("_________________________________________", margin, y);
  y += lineHeight;
  doc.text("(Printed Name)", margin, y);
  y += lineHeight * 2;
  
  doc.text("_________________________________________", margin, y);
  y += lineHeight;
  doc.text("_________________________________________", margin, y);
  y += lineHeight;
  doc.text("(Mailing Address)", margin, y);
  y += lineHeight * 2;
  
  doc.text("Phone: __________________________________", margin, y);
  
  // Footer note
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by TaxedHQ. This document is for educational purposes and does not constitute legal or tax advice.", margin, 792 - margin);
  
  // Save the PDF
  doc.save("IRS_Penalty_Abatement_Request.pdf");
}
